### ISSUE TITLE
 Unexpected token

### ISSUE THREAD

**Issue by KarelWintersky** [beyondit/map-tiles-crawler#1]
```
Crawler.prototype.getPaths = function (url, tile, targetPrefix = '') {
                                                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Arris\AppData\Roaming\npm\node_modules\map-tiles-crawler\bin\mtc.js:5:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by stefanhuber** [comment]
thx for your feedback.

optional parameters are supported with node version >= 6.
